# Generated by Django 4.2.2 on 2023-08-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbase",
            name="about",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="address_line_1",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="address_line_2",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="country",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="postcode",
        ),
        migrations.RemoveField(
            model_name="userbase",
            name="town_city",
        ),
    ]
