# Generated by Django 4.2.2 on 2023-08-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0003_remove_userbase_about_remove_userbase_address_line_1_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="customer",
            new_name="user",
        ),
    ]
