# Generated by Django 4.2.2 on 2023-08-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_by",
        ),
    ]
